<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="cart_sidebar">
            <block class="Ashish\UserStory19\Block\Cart\Sidebar" name="cross_sell_products" template="Ashish_UserStory19::cross_sell.phtml"/>
        </referenceBlock>
    </body>
</page>